### ISSUE TITLE
Add support for Observables

### ISSUE THREAD

**Issue by garadox** [openzipkin-contrib/brave-ratpack#11]
I already have a workaround to support RxJava Observable workloads (rather than using TracedParallelBatch Promises), but it relies on direct access to the `TraceContextHolder` class which is marked private. This appears to only work in Groovy.

Please add additional options for passing the trace context across threads, or allow users to manually set the trace context back after we switch threads so the Trace code can find it.

Example workaround:

```
def tracer = Tracing?.current()?.tracer()
TraceContext context = tracer.currentSpan()?.context()
dev action = Observable.just("test")

action.doOnSubscribe {
  Execution.current().add(new RatpackCurrentTraceContext.TraceContextHolder(context))

  tracer.currentSpan().tag("test key", "test value")  
}.subscribe()

```

**Comment by devinsba** [comment]
I understand not wanting to have to rely on reflection for things, in lieu of help from a Ratpack expert there are a couple things I can see that might work. There is a deprecated method on `RatpackCurrentTraceContext` that you could use instead of having to rely on reflection: `RatpackCurrentTraceContext.wrap(TraceContext)`

I'm also seeing maybe wrapping your `Execution.current()` with: `TracingPropagationExecInitializer.init(Execution)` would do what you are looking for.

**Comment by garadox** [comment]
Is `TracingPropagationExecInitializer` a new class? I'm not finding that class in this repo or in the main brave repo.

**Comment by devinsba** [comment]
Sorry, its an sub-class (internal?) in `RatpackCurrentTraceContext`

**Comment by garadox** [comment]
Hmm, i'm not seeing that class in version 2.3.2 .

**Comment by garadox** [comment]
It was added Jan 4th, but 2.3.2 was released Jan 2nd.

**Comment by kirenjolly** [comment]
@hyleung @llinder @adriancole @beckje01  Can you make a new release of the Current master branch code with `TracingPropagationExecInitializer.init(Execution)` ASAP. Since Our application in production is using Ratpack and Kotlin and are facing issues as TraceContext is not propagated properly and doesn't have any public functions to manually update `TraceContext`  in TraceContextHolder .

**Comment by llinder** [comment]
Started a release of 2.4.0.

Part of the reason for making some of these things private is to avoid breaking things if we decided to change internal pieces.  Also it forces us to look at the reason the work around is necessary and try to solve it in a way that doesn't require work arounds.  Fortunately in this case Ratpack 1.6 added what we always needed and @beckje01 was quick to address this.

@garadox do you feel that the ExecInitializer will solve problems you have with Ratpack Observables?

**Comment by llinder** [comment]
Release of 2.4.0 is done.  Just waiting on Maven Central to update with the synced artifacts.

**Comment by garadox** [comment]
@llinder Yes, I believe the ExecInitializer will address my current workaround (It's use of `execution.maybeParent` and being non-private is the key).

**Comment by garadox** [comment]
Ah, I just realized the Ratpack 1.6 dependency. We can't test this yet but i'll close the issue and come back once we've upgraded if there are still issues.
